export default {    
    /* Sound IDs */
    //seawaves: 'seawaves',
    summer_day: 'summer_day',
    thunderstorm: 'thunderstorm',
    summer_night: 'summer_night',
    kitty_purr: 'kitty_purr',
    campfire: 'campfire',
    inside_train: 'inside_train',
    deep_space: 'deep_space',    
    october_rain: 'october_rain',
    river_stream: 'river_stream',
    sailing_yacht: 'sailing_yacht',
    farm: 'farm',
    city_street: 'city_street',    
    //paris_cafe: 'paris_cafe',
    //birds_in_park: 'birds_in_park',
    wind_chimes: 'wind_chimes',
    //REASON:incorreact clock phase because trimmed sound
    //clock: 'clock',
    //crickets: 'crickets',
    //REASON: too big size
    //desert: 'desert',
    ghosty: 'ghosty',
    heartbeat: 'heartbeat',
    vinyl_cracks: 'vinyl_cracks',
    blue_whales: 'blue_whales',
    magic_chimes: 'magic_chimes',
    night_owls: 'night_owls',
    playground: 'playground',
    white_noise: 'white_noise',
    pink_noise: 'pink_noise',
    
    ship_hull: 'ship_hull',
    space_drone: 'space_drone',
    subway: 'subway',
    tropical_birds: 'tropical_birds',
    typewriter: 'typewriter',
    keyboard: 'keyboard'
};
