export default {    
    /* Sound IDs */
    //seawaves: 'seawaves',
    sy: 'summer_day',
    tm: 'thunderstorm',
    st: 'summer_night',
    kr: 'kitty_purr',
    ce: 'campfire',
    in: 'inside_train',
    de: 'deep_space',
    on: 'october_rain',
    rm: 'river_stream',
    sh: 'sailing_yacht',
    fm: 'farm',
    ct: 'city_street',
    //paris_cafe: 'paris_cafe',
    //birds_in_park: 'birds_in_park',
    ws: 'wind_chimes',
    //REASON:incorreact clock phase because trimmed sound
    //clock: 'clock',
    //crickets: 'crickets',
    //REASON: too big size
    //desert: 'desert',
    gy: 'ghosty',
    ht: 'heartbeat',
    vs: 'vinyl_cracks',
    bs: 'blue_whales',
    ms: 'magic_chimes',
    ns: 'night_owls',
    pd: 'playground',
    wn: 'white_noise',
    pe: 'pink_noise',
    
    sl: 'ship_hull',
    se: 'space_drone',
    sa: 'subway',
    ts: 'tropical_birds',
    tr: 'typewriter',
    kb: 'keyboard'
};
